const express = require('express')
const router = express.Router()
const admin = require('./modules/admin')
const restController = require('../../controllers/apis/restaurant-controller')
const adminController = require('../../controllers/apis/admin-controller')
const { apiErrorHandler } = require('../../middleware/error-handler')
router.use('/admin', admin)
router.get('/restaurants', restController.getRestaurants)
router.delete('/restaurants/:id', adminController.deleteRestaurant)
router.use('/', apiErrorHandler)
module.exports = router
